### ISSUE TITLE
Crystalline needs to be updated for crossfade

### ISSUE THREAD

**Issue by aure** [PaulBatchelor/the_sporth_cookbook#4]
Expected 3 arguments on the stack, but there are only 2!

--
Might fix this myself, but making a note  just in case.

**Comment by PaulBatchelor** [comment]
It's a bit more complicated than that. I see two ugens whose arguments have changed... mincer and tblrec. Trivial enough to fix, but you may have to update mincer and tblrec.

**Comment by aure** [comment]
pretty sure i'm up to date with those.  Does Crystalline work for you?

**Comment by PaulBatchelor** [comment]
oh it looks like there are some sporth changes that need to be pushed. hold on...

**Comment by PaulBatchelor** [comment]
Changes pushed to Sporth and here. Can you try again? I'm also assuming you are up-to-date with soundpipe dev as well.

**Comment by aure** [comment]
I updated soundpipe and sporth and crystalline, but I get the same error

p0: "0",
p1: "0",
p2: "0",
p2: "0",
Expected 3 arguments on the stack, but there are only 2!
Not enough arguments for crossfade
cf returned an error.
Did not recompile...
Sporth Based Generator(91821,0x1126f73c0) malloc: *** error for object 0x13b9: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug

**Comment by PaulBatchelor** [comment]
Try the sporth commandline and see if it bugs out. Things work fine for me using that.

**Comment by PaulBatchelor** [comment]
Also, are you certain that you are updating crystalline? For instances, make sure this line matches:

https://github.com/PaulBatchelor/the_sporth_cookbook/blob/master/crystalline/crystalline.sp#L174

**Comment by aure** [comment]
Working from the command line so I guess something is still out of date within ak

**Comment by aure** [comment]
All of my modules and ugens seem to be identical.

**Comment by PaulBatchelor** [comment]
how very interesting... 

are you certain that crystalline itself is being updated okay?

**Comment by aure** [comment]
yes.

**Comment by PaulBatchelor** [comment]
@aure I don't believe you... yet. send me a screen shot of the editor with this line:

https://github.com/PaulBatchelor/the_sporth_cookbook/blob/master/crystalline/crystalline.sp#L174

**Comment by PaulBatchelor** [comment]
~~also send me code from mincer and tblrec, both soundpipe and ugens~~

This code is fine in AK dev.
